services:
  backend:
    build: .
    container_name: app-nodejs
    depends_on:
      - mysql
    ports:
      - 3000:3000
    networks:
      - app-network-node
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - data_mysql:/var/lib/mysql
    networks:
      - app-network-node
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE


networks:
  app-network-node:
    driver: bridge
volumes:
  data_mysql: